- pyout.py
- test_pyout.py
```
Make Tabular.rewrite take a dictionary with {column: value, ...} to
identify the row to rewrite.  This way, we don't force the caller
specify the id column at instance creation.  Also, we can easily
support a multi-column id without having to worry about making
__init__'s id_column and rewrite's ids take both single and
multi-value forms.
The tradeoff is that the rewrite call is a little more verbose for
simple cases, but the intention should also be clearer (the
column->value mapping is right there so you don't have to think "oh
yeah, that first value is a value for id column").
```
Follow up to https://github.com/pyout/pyout/pull/14#discussion_r158509081
> ENH+RF: Drop id_column argument, support multi-column id

- setup.py
... since pyout will currently fail on Windows.
Re: #4, #13, #27
> setup.py (classifiers): Specify POSIX for OS

- CHANGELOG.md
- pyout/elements.py
- pyout/field.py
- pyout/tabular.py
- pyout/tests/test_field.py
- pyout/tests/test_tabular.py
You can now add a style entry in the form of
`"<column>": {"transform": <function>}`, where `function` takes a
single argument and returns a transformed value.
As an example,
```
from humanize import naturalsize
out = Tabular(columns=["name", "size", "path"],
style={
"header_": {"transform": str.upper},
"separator_": " | ",
"size": {"transform": naturalsize,
"color": {"interval": [[5000, None, "red"]]}}})
out({"name": "x", "size": 3, "path": "/tmp/x"})
out({"name": "y", "size": 3000, "path": "/tmp/y"})
out({"name": "z", "size": 300000000, "path": "/tmp/z"})
```
outputs
```
NAME | SIZE     | PATH
x    | 3 Bytes  | /tmp/x
y    | 3.0 kB   | /tmp/y
z    | 300.0 MB | /tmp/z
```
(with the last size field in red)
Closes #23.
> ENH: Support transform function (e.g., humanize.naturalsize) via style

- CHANGELOG.md
- pyout/tabular.py
- pyout/tests/test_tabular.py
Now `x` in `"col": ("initial value", x)` can be a generator function
or generator object in addition to a normal function.
For a demo, try
```
import time
def check():
for idx, update in enumerate(["doomed", "or....", "allgoodsir"]):
time.sleep(idx)
yield update
rows = [{"name": "abc", "status": "installed"},
{"name": "abc00", "status": ("waiting", check)},
{"name": "abc01", "status": "installed"},
{"name": "abc02", "status": "installed"}]
style = {"status": {"color":
{"label": {"allgoodsir": "green",
"doomed": "red"}}}}
with Tabular(["name", "status"], style=style) as out:
for row in rows:
out(row)
```
> ENH: Allow field values to be a generator (function)

- pyout/tests/test_tabular.py
d63577ec (ENH: Allow field values to be a generator (function),
2018-01-31) wired up generators to the same underlying callback
function that's used for regular functions, so this should just work,
but we might as well add a test to make sure there's not an unforeseen
interaction.
Re: #34
> TST: tabular: Explicitly test 'generator -> multi-column' case

- pyout/tabular.py
- pyout/tests/test_tabular.py
This makes it easier to use callable when the data accessed via an
objects attributes, though this still won't work well with properties.
We might want to export a style key like "initial value" so that the
user can specify something other than an empty string.
> ENH: tabular: Don't require initial values for callables

- pyout/elements.py
- pyout/field.py
- pyout/tabular.py
- pyout/tests/test_field.py
- pyout/tests/test_tabular.py
* Provide a class to represent missing values and don't call the
transformers if we encounter it.
* If the passed data is missing a column's key/attribute, fill it in
with a missing value.
Closes #37.
> Allow incomplete records

- pyout/field.py
- pyout/tests/test_tabular.py
Prevent an error when a non-hashable is passed for a column that has a
label style.
Re: https://github.com/pyout/pyout/issues/46#issuecomment-364713320
> BF: by_lookup: Allow non-hashable values

- pyout/common.py
- pyout/elements.py
- pyout/field.py
- pyout/tabular.py
- pyout/tests/test_tabular.py
The last commit of this series adds the ability to "delay" accessing a column's value by wrapping it in a callable.  The delayed values can be grouped by using the same string.
This change forced me to deal (at least partially) with Tabular's bloat rather than add to it.  The other commits in this series do that restructuring or related cleanup.
This is the relevant diff for the delayed feature: https://github.com/pyout/pyout/compare/928363735749d2f85c0827bc8dd3165c241080e4...f22841058581ff0bd4341af3974137b1e8e0ab87
------------------------------------------------------------------------
demo:
```python
import time
class Data(object):
def __init__(self, name, path, status, date):
self.name = name
self._path = path
self._status = status
self.date = date
@property …
```
> ENH: Add "delayed" style key

- pyout/__init__.py
- pyout/common.py
- pyout/elements.py
- pyout/field.py
- pyout/summary.py
- pyout/tabular.py
- pyout/tests/test_elements.py
- pyout/tests/test_field.py
- pyout/tests/test_summary.py
- pyout/tests/test_tabular.py
The main commit of interest is 3ae077cc9ca5d5022a3a194c53bc08adb7ad04f4.
@yarikoptic, how do you feel about the "aggregate" name?  I chose it over "summary" for two reasons:
* I like that it is a verb (in line with "transform").  As verbs goes, "summarize" would work, but "aggregate" came to mind because of pandas (of course we're limiting ourselves to one axis here...).
* For the summary row styles, I added the special key "summary_" (consistent with "header_") and in that case "summary" and "summary_" seem confusingly close.
------------------------------------------------------------------------
And here's a quick demo:
```python
from collections import Counter
import time
def check():
for idx, update in enumerate([{"items": 2},
{"items": 20, "status": …
```
> Add support for summary lines

- CHANGELOG.md
- pyout/common.py
- pyout/elements.py
- pyout/field.py
- pyout/tabular.py
- pyout/tests/test_elements.py
- pyout/tests/test_field.py
- pyout/tests/test_tabular.py
```
If the width of a row exceeds the terminal's width, it wraps into the
next line and breaks all of our line counting-based modifications.  To
deal with this, we need truncate fields so that the row is within the
available width.  Note that we can't simply truncate at the row-level
because each field by include escape sequences.
```
> BF: Truncate fields to avoid exceeding terminal width

- CHANGELOG.md
- pyout/interface.py
- pyout/tabular.py
- pyout/tests/test_tabular.py
This PR fixes #42 by implementing the repaint solution proposed [here](https://github.com/pyout/pyout/issues/42#issuecomment-446732802).
Using the `datalad ls` command from #42 with cleared caches, I didn't observe the issue after applying these changes (or more accurately, an earlier version of the changes: f4e40f677e489a).
>  BF: interface: Prevent callbacks trying to update offscreen

- CHANGELOG.md
- pyout/common.py
- pyout/elements.py
- pyout/field.py
- pyout/tests/test_field.py
- pyout/tests/test_tabular.py
- pyout/tests/test_truncate.py
- pyout/truncate.py
Support specifying the truncation style with `<col>: {"width": {"truncate_at": VAL}`, where VAL is "left", "center", or "right".
Any other ideas for the key name instead of "truncate_at"?
> ENH: Support left and center truncation styles

- CHANGELOG.md
- pyout/elements.py
- pyout/field.py
- pyout/tests/test_tabular.py
Add new style attribute `re_lookup` (and associated `re_flags` attribute).
---
Demo:
```python
#!/usr/bin/python3
rows = [
{"name": "foo", "status": "ok"},
{"name": "bar", "status": "DOOMED"},
{"name": "baz", "status": "unknown"}
]
style = {"status": {"color":
{"re_lookup": [["(good|ok)", "green"],
["^doomed$", "red"]]},
"re_flags": ["I"]}}
with Tabular(["name", "status"], style=style) as out:
for row in rows:
out(row)
```
> NF: Support styling values based on regular expression matching

- CHANGELOG.md
- README.rst
- appveyor.yml
- pyout/__init__.py
- pyout/interface.py
- pyout/tabular_dummy.py
- pyout/tests/test_tabular.py
- pyout/tests/test_tabular_dummy.py
- setup.py
On Windows replace the `Tabular` with one that doesn't support styling or updating previous lines.
Let's see how the AppVeyor run goes.
> Minimally useful execution on Windows

- pyout/field.py
- pyout/tests/test_tabular.py
The processor doesn't necessarily receive a string value.  Some common
cases are Nothing() objects for asynchronous values and numbers.
Pass the result for non-string values back untouched.
Another option would be to convert it to a string.  That could lead to
unintentional matches on str(object), but at the same time, that _is_
what will be shown, so perhaps it wouldn't be surprising.  For now, go
with the stricter route, adding a test that demonstrates the behavior.
We can revisit it if needed.
> re_lookup: Guard against non-string values

- CHANGELOG.md
- pyout/common.py
- pyout/interface.py
- pyout/tests/test_tabular.py
```
Callers usually know the row values because they are passing them in
directly.  However, if values are being populated asynchronously (say
a function that connects to a remote and checks the status), callers
don't have an easy way to access them even though the values may be of
interest.
Give callers access to a row's value via __getitem__().
```
> interface: Provide callers access to row values

- pyout/tests/test_tabular.py
```
As of ea4156ee (BF: Raise StyleFunctionError with original traceback,
2018-02-11), when a transform function raises an exception, we embed
the original traceback so that we don't assume the caller handled the
exception in a way that preserves the original traceback.  The
motivating example for this was DataLad's exc_str() helper, which uses
extract_tb() underneath [*].
The regression test added in ea4156ee uses format_exception(), but
that only catches the issue under Python 2; under Python 3 the
original exception is included in the output.
Switch to using extract_tb() so that this regression test is effective
under Python 3 (which is important because we are about to drop Python
2 support).
[*] ... though, in light of Python 3's explicit chaining, exc_str() is
arguably flawed.
```
> Extend test of StyleFunctionError's embedded traceback to Python 3

- CHANGELOG.md
- pyout/common.py
- pyout/elements.py
- pyout/summary.py
- pyout/tests/test_summary.py
- pyout/tests/test_tabular.py
- setup.py
pyout requires that all columns are specified before writing begins.
If none are explicitly specified, it infers the list of columns from
the first record received.
For some uses cases, it'd be desirable to expand the list of columns
as new keys are encountered (gh-49).  Unfortunately many parts of
pyout assume that the set of columns is fixed, so adding support for
auto-expanding the column list seems like it will require pretty deep
changes.  The issue is complicated by the fact that the request
involves more than being able to give records with new keys when
calling Tabular: asynchronous callbacks, themselves specified as
values to some column(s), should also be able to create new columns.
One of the motivations for auto-expanding the column list is the
desire to not show columns …
> Support hiding columns

- CHANGELOG.md
- pyout/common.py
- pyout/elements.py
- pyout/tests/test_tabular.py
- setup.py
This draft reworks how we assign widths to the auto-width columns.  It tries to address the [issues mentioned][0] at the "hide columns" pull request (gh-86).  This series will have a lot of interaction with gh-86, and I still need to check how well that one plays on top of this one.
This also adds support for specifying width values as a fraction of the overall table width (gh-85).
[0]: https://github.com/pyout/pyout/pull/86#issuecomment-542427707
> auto-widths: Distribute width more evenly across columns

- CHANGELOG.md
- pyout/common.py
- pyout/elements.py
- pyout/interface.py
- pyout/tests/test_tabular.py
If the stream isn't attached to a tty, it makes sense to let the
columns have as much space as needed, particularly in the case of the
output being redirected to a file.
When non-interactive, Stream.width already returns None.  Teach the
downstream code that None should be treated as unlimited available
width.
Closes #70.
> Support an unbounded table width for non-interactive streams

- CHANGELOG.md
- pyout/common.py
- pyout/interface.py
- pyout/tabular.py
- pyout/tabular_dummy.py
- pyout/tests/test_interface.py
- pyout/tests/test_tabular.py
- pyout/tests/test_tabular_dummy.py
This is a work-in-progress series that switches from using `multiprocessing.dummy.Pool` to `concurrent.futures.ThreadPoolExecutor`.  The main motivation is to improve the exception reporting for asynchronous row values (#94).
> Rework asynchronous execution to use concurrent.futures

- pyout/tests/test_tabular.py
test_tabular_write_callable_kb_interrupt_in_exit is failing in some
outside builds (gh-103) in a way that hasn't occurred on Travis or for
me locally.  The failure is due to the stream lacking the output from
the asynchronous callables.
There is a race between writing the callable output when the Delayed()
callable is marked as ready and raising the artificial
KeyboardInterrupt exception.  I can trigger this locally when I slow
down the callable by adding a sleep (say 3 seconds) right before
Delayed().run() returns.
Avoid this race by not raising the KeyboardInterrupt until the delayed
output has reached its destination.  Don't worry about hanging because
these test are already marked with pytest.mark.timeout().
Closes #103.
> Avoid race in keyboard interrupt tests

- pyout/common.py
- pyout/interface.py
- pyout/tests/test_tabular.py
This series implements the second option discussed at gh-102:
> As discussed before (e.g., gh-49 and gh-86), pyout relies on knowing all the columns up front, so I think this spot is right to assume that a column name is in `hidden`. I'd say it's upstream code that should do one of the following if asynchronous function provides an unknown columns: (1) error or (2) filter it out. I'm leaning toward no. 2 because I'm not sure there's anything gained by being stricter here. I'll look into where I think the best spot to do this is.
The second commit in particular resolves the specific failure from gh-102.
> Prevent unknown columns from coming in via asynchronous callables

- CHANGELOG.md
- pyout/common.py
- pyout/interface.py
- pyout/tests/test_tabular.py
Lift the requirement that the set of columns be known up front.
Ideally this should be done in a single spot, because scattering
dict.get() and other handling throughout the code will be hard to
reason about and is likely to be a source of bugs.
Get close to that goal by making StyleFields.render() raise an
exception when it encounters an unknown column and then have _write(),
which importantly is working with an acquired lock, do the necessary
re-initializations.
Adjust some upstream spots to let unknown columns through, including
reverting the filtering of unknown columns from c21579bb (Merge pull
request #108 from kyleam/filter-unknown-cols, 2020-06-01).  Having the
upstream code itself register the new columns doesn't work well
because new columns can come in through plain values …
> Support expanding set of known columns

- CHANGELOG.md
- pyout/interface.py
- pyout/tests/test_tabular.py
Tabular's `columns` parameter is documented as accepting a list of str
or an OrderedDict, but, until 373f664e (Support expanding set of known
columns, 2020-06-10), it also happened to tolerate tuples and probably
some other sequences.  At least one spot in third-party code already
passes a tuple, so make this work again.
Closes #110.
> interface: Try to coerce undocumented types to a list

- .travis.yml
- CHANGELOG.md
- README.rst
- appveyor.yml
- setup.py
The latest Travis build with Python 3.4 failed with
pyrsistent requires Python '>=3.5' but the running Python is 3.4.8
Rather than try to pin versions to work around this, bump pyout's
minimum Python version to 3.6.  This matches the minimum of dandi-cli,
the main project that uses pyout.
Ref: https://travis-ci.org/github/pyout/pyout/jobs/728570815#L228
> Bump minimum Python version to 3.6

- pyout/field.py
- pyout/tests/test_tabular.py
The Flanks class chops off flanking whitespace before applying the
other post-format processors and then adds back the whitespace
afterward.  This prevents, for example, underlining the flanking
whitespace.
The regexp that matches the flanking whitespace should always match,
but it doesn't account for the fact that the caller could pass in a
value with newlines.  A field with newlines will break pyout in other
ways (e.g., line updates), so we may want to consider escaping values
to prevent this.  But either way, a value with newlines shouldn't
trigger a failure in the Flanks processor, so adjust the regexp to
allow for newlines.
Closes #104.
Closes #115.
> field: Match newlines with Flanks regexp

- pyout/tabular.py
These two commits deal with the Jupyter issues reported in gh-118 and gh-120.  Based on my local testing, this leads to Jupyter having the same "final" output you'd get when redirecting the output to a file.  That's an improvement over what's reported in those issues, but more work would be needed to get nice notebook rendering.
> Minor Jupyter tweaks

- .travis.yml
conda started to build for 3.9 but there are some inconsistent results
https://github.com/conda-forge/pyout-feedstock/pull/7
wanted to see if travis already has 3.9, how well it would work
> Add python 3.9 into matrix

- CHANGELOG.md
- pyout/interface.py
- pyout/tests/test_tabular.py
pyout's update logic is easily thrown off if callers write to the
screen.  Provide a method that callers can use to block pyout
(optionally clearing the table), write output, and then restore the
table's content.
Output can of course come from many places that callers do not expect
or control, so this is only helpful in a subset of cases.
> interface: Add outside_write() context manager

- CHANGELOG.md
- pyout/interface.py
- pyout/tests/test_tabular.py
If a table has a summary, _write_update() clears it.  However, the
write function is called a second time if an unknown column is
encountered.  In that case, there's no summary to clear, leading to
the counts being off and lines upstream of the first row being
overwritten.
Extend the write functions with a parameter to enable distinguishing
the first and second call so that write functions can avoid any logic
that shouldn't be repeated.
Closes #128.
> interface: Don't try to clear summary more than once

- pyout/elements.py
Fixes #130.
The JSON Schema used by pyout currently lacks a `"$schema"` key declaring what version of the JSON Schema standard it uses.  This causes the jsonschema library to validate it using the latest released draft; this draft changed in version 4.0 of the library from Draft 7 to Draft 2020-12, hence the failures reported in #130.
This PR adds an explicit `"$schema"` key to pyout's JSON schema that declares it as following JSON Schema Draft 7.
> Declare JSON schema as following Draft 7

- .coveragerc
- .github/workflows/test.yml
- appveyor.yml
- pytest.ini
- setup.cfg
- setup.py
- tox.ini
`setup.py test` is deprecated.  Use `tox` instead.
Also update & improve some other infrastructure elements.
> Stop using `setup.py test`

- pyout/elements.py
- pyout/tests/conftest.py
- pyout/tests/test_elements.py
While troubleshooting slow "dandi download" we saw that considerable amount of time is spent on jsonschema validation (and logging, not considered here). See https://github.com/dandi/dandi-cli/issues/1549
It is happening since we be providing styling per each row, which might differ for summary line etc. And we might be re-validating over and over again. The obvious solution, without trying to fix logic upstairs, is to use @lru_cache.  But it could be not used as-is since style is a dict (mutable), nested, and can have function callbacks.  Conversion of such style to `str` is relatively fast and should be good enough for jsonschema validation.  Unfortunately an initial attempt to just wrap into some "Hashable" instance lead to jsonschema pukes.
So I decided to wrap/unwrap the value and …
> OPT: cache validation of styles
